default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: u332593518_ikasle_tasker
  password: QWERT!@34qwert
  host: srv1639.hstgr.io

development:
  <<: *default
  database: u332593518_ikasle_tasker

test:
  <<: *default
  database: tasker_test

production:
  <<: *default
  database: u332593518_ikasle_tasker
  username: u332593518_ikasle_tasker
  password: QWERT!@34qwert